### ISSUE TITLE
Creator Tools Fehlerhafte moddesc

### ISSUE THREAD

**Issue by darkroygamer** [TyKonKet/FS17_CreatorTools#19]
Ich habe creator Tools installiert es wird mir im Spiel nicht angezeigt und auch nicht im ingame modhub was ist da los 

p.s. ich habe die steam Version.

**Comment by TyKonKet** [comment]
I think this problem is solved in the new version currently in testing on modhub.
Let me know!

**Comment by darkroygamer** [comment]
Ok Dankeschön, hatte mich schon gewundert weil der Mod im modhub nicht mehr angezeigt wurde
