### ISSUE TITLE
Add French translate

### ISSUE THREAD

**Issue by naej56** [TyKonKet/FS17_CreatorTools#6]
Hello,
I have translate in french this mods, but i don't know how to pull request.
I am new on github and don't know how it works.

I have "fork" this depot whitout problem and create branch, but i can't pull request, i don't get the right.
How can i send you my work ?

Sorry for my bad english.

**Comment by TyKonKet** [comment]
I don't see your fork, are you sure you have forked this repository or you have only cloned it?

**Comment by naej56** [comment]
My bad, i clone it and don't fork it.
I will try with fork thx.

Edit : I have fork and add a pull request. I hope it's the right way to do.

**Comment by TyKonKet** [comment]
Ok, now I can see your fork but I don't see any pull request, if you prefer I can do it for you (at least I think)

**Comment by naej56** [comment]
I really don't understand how github works.
I give a link the files if you want add them to your github.
[https://drive.google.com/open?id=0BxGYADbYaWeLZG1tamg1Q1ItUEU](url)
Sorry for the desagrement and thx for the help

**Comment by TyKonKet** [comment]
Ok, now you have done the pull request in the right way, nice job and thanks for help, if you also want to help me with other mods translations you can find them on my GitHub profile:
https://github.com/TyKonKet

**Comment by naej56** [comment]
Ok, thx to you for the help, i will watch the other mods and try to translate them to.
