### ISSUE TITLE
Conflict with manualAttaching mod

### ISSUE THREAD

**Issue by Gonimy-Vetrom** [TyKonKet/FS17_CreatorTools#9]
I have a conflict of these two mods. There is no error in the log. But the technique does not want to join.
http://www.farming-simulator.com/mod.php?lang=en&country=ru&mod_id=67536&title=fs2017

**Comment by TyKonKet** [comment]
@Gonimy-Vetrom 
The problem is caused by the overlapping of "Q" and "Z" inputs, any suggestion on possible solutions?
